package univ.StockManger.StockManger.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import jakarta.persistence.EntityNotFoundException;
import org.springframework.stereotype.Service;
import univ.StockManger.StockManger.entity.Bon;
import univ.StockManger.StockManger.entity.LigneBon;
import univ.StockManger.StockManger.entity.Rapport;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;

@Service
public class PdfGeneratorService {

    public byte[] generatePdf(Rapport rapport, List<Bon> bons) throws DocumentException, IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, baos);

        document.open();

        Font fontTitle = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, Color.BLACK);
        Paragraph title = new Paragraph("Monthly Report", fontTitle);
        title.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(title);
        document.add(new Paragraph(" ")); // Spacer

        // Report Metadata
        document.add(new Paragraph("Report Type: " + (rapport.getReportType() != null ? rapport.getReportType() : "N/A")));
        
        // Add Generated By info
        String generatedByName = "System Generated";
        if (rapport.getGeneratedBy() != null) {
            generatedByName = rapport.getGeneratedBy().getNom() + " " + rapport.getGeneratedBy().getPrenom();
            if (rapport.getGeneratedBy().isDeleted()) {
                generatedByName += " (Deleted User)";
            }
        }
        document.add(new Paragraph("Generated By: " + generatedByName));
        
        document.add(new Paragraph("Generation Date: " + (rapport.getDateGeneration() != null ? rapport.getDateGeneration() : "N/A")));
        document.add(new Paragraph("Period: " + rapport.getStartDate() + " to " + rapport.getEndDate()));
        document.add(new Paragraph("Total Expense: " + String.format("%.2f", rapport.getTotalExpense() != null ? rapport.getTotalExpense() : 0.0)));
        document.add(new Paragraph(" ")); // Spacer

        if (bons == null || bons.isEmpty()) {
            Paragraph noData = new Paragraph("No transactions found for this period.", FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 12, Color.RED));
            noData.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(noData);
        } else {
            // Table of Details
            PdfPTable table = new PdfPTable(5);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{2, 4, 2, 2, 2});

            addTableHeader(table);
            addRows(table, bons);

            document.add(table);
        }

        document.close();

        return baos.toByteArray();
    }

    private void addTableHeader(PdfPTable table) {
        String[] headers = {"Date", "Product", "Quantity", "Unit Price", "Total"};
        for (String header : headers) {
            PdfPCell headerCell = new PdfPCell();
            headerCell.setBackgroundColor(Color.LIGHT_GRAY);
            headerCell.setPadding(5);
            headerCell.setPhrase(new Phrase(header));
            table.addCell(headerCell);
        }
    }

    private void addRows(PdfPTable table, List<Bon> bons) {
        for (Bon bon : bons) {
            if (bon.getLignesBon() != null) {
                for (LigneBon ligne : bon.getLignesBon()) {
                    String productName;
                    double unitPrice;
                    double total;
                    
                    try {
                        // Try to access product details safely
                        if (ligne.getProduit() != null) {
                            productName = ligne.getProduit().getNom() != null ? ligne.getProduit().getNom() : "Unknown";
                            unitPrice = ligne.getProduit().getPrixUnitaire();
                            total = ligne.getQuantite() * unitPrice;
                        } else {
                            // Should not happen if DB is consistent, but handle it
                            productName = "Unknown Product";
                            unitPrice = 0.0;
                            total = 0.0;
                        }
                    } catch (Exception e) {
                        // Handle deleted product (EntityNotFoundException or others)
                        productName = "Deleted Product";
                        unitPrice = 0.0;
                        total = 0.0;
                    }

                    // Now add cells to the table atomically
                    String dateStr = (bon.getDate() != null) ? bon.getDate().toString() : "N/A";
                    table.addCell(dateStr);
                    table.addCell(productName);
                    table.addCell(String.valueOf(ligne.getQuantite()));
                    table.addCell(String.format("%.2f", unitPrice));
                    table.addCell(String.format("%.2f", total));
                }
            }
        }
    }
    
    public byte[] generateBonPdf(Bon bon) throws DocumentException, IOException {
        return new byte[0];
    }
}
